spring.application.name=helpdesk

# My backend will run on this port
server.port=8080

# this is my db connection center. it will automatically be created if it does not exist. 
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=robert1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# databse config end here

# // Hibernate properties allow the jpa to automatically create and update the database schema based on the entity classes.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


